apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mumbleserver.fullname" . }}
  labels:
    {{- include "mumbleserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mumbleserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mumbleserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mumbleserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: letsencrypt-data
        - name: murmur-data
      initContainers:
        - name: fill-volumes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: letsencrypt-data
              mountPath: /tgt/le
            - name: murmur-data
              mountPath: /tgt/murmurdata
          command:
            - /bin/bash
            - -c
            - >
              cp -a /etc/letsencrypt/./ /tgt/le/ &&
              cp -a /murmurdata/./ /tgt/murmurdata/ &&
              ls -R /tgt/le /tgt/murmurdata
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # TODO: Remove this when we are production ready
            - name: "CERTBOT_EXTRA_ARGS"
              value: "--test-cert"
            {{- if .Values.mumble.disable_tls }}
            - name: "NO_TLS"
              value: "1"
            {{- end }}
            {{- if or .Values.use_certmanager .Values.mumble.disable_tls }}
            - name: "NO_CERTBOT"
              value: "1"
            {{- end }}
            - name: "SERVER_DOMAIN"
              value: {{ required "A valid .Values.mumble.server_domain entry required!" .Values.mumble.server_domain }}
            - name: "CERTBOT_EMAIL"
              value: {{ required "A valid .Values.mumble.certbot_email entry required!" .Values.mumble.certbot_email }}
            - name: "SERVER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: server_password
                  name: {{ .Release.Name }}-auth
            - name: "SUPERUSER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: superuser_password
                  name: {{ .Release.Name }}-auth
          ports:
            {{- if and (not .Values.use_certmanager) (not .Values.mumble.disable_tls) }}
            - name: http
              containerPort: 80
              protocol: TCP
            {{- end }}
            - name: mumble-tcp
              containerPort: 64738
              protocol: TCP
            - name: mumble-udp
              containerPort: 64738
              protocol: UDP
          livenessProbe:
            exec:
              command:
                - pgrep
                - murmurd
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - >
                  pgrep certbot || pgrep murmurd
            initialDelaySeconds: 1
            periodSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /murmurdata
              name: murmur-data
            - mountPath: /etc/letsencrypt
              name: letsencrypt-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
